# GTFS-RT Configuration File

# Global storage configuration (used as default)
[storage]
type = "filesystem"  # Options: "filesystem", "gcs", or "minio"
[storage.params]
base_directory = "data"  # Base directory for filesystem storage

# For Google Cloud Storage, use:
# type = "gcs"
# [storage.params]
# bucket_name = "your-bucket-name"
# base_path = "gtfs-rt"  # Optional base path within the bucket

# For MinIO Storage, use:
# type = "minio"
# [storage.params]
# endpoint = "minio.example.com:9000"  # MinIO server endpoint without http/https
# access_key = "your-access-key"
# secret_key = "your-secret-key"
# bucket_name = "your-bucket-name"
# secure = true  # Use HTTPS (true) or HTTP (false)
# base_path = "gtfs-rt"  # Optional base path within the bucket

# Provider configurations
[[providers]]
name = "ovapi"
timezone = "Europe/Amsterdam"

  # Provider-specific storage (overrides global)
  [providers.storage]
  type = "filesystem"
  [providers.storage.params]
  base_directory = "data/ovapi-specific"  # Different directory for this provider

  [[providers.apis]]
  url = "https://gtfs.ovapi.nl/nl/vehiclePositions.pb"
  services = ["VehiclePosition"]
  refresh_seconds = 20  # Fetch every 20 seconds
  frequency_minutes = 5  # Group files in 60-minute intervals
  check_interval_seconds = 10  # Check for new files every 5 minutes

  [[providers.apis]]
  url = "https://gtfs.ovapi.nl/nl/tripUpdates.pb"
  services = ["TripUpdate"]
  refresh_seconds = 30  # Fetch every 30 seconds
  frequency_minutes = 60  # Group files in 60-minute intervals
  check_interval_seconds = 300  # Check for new files every 5 minutes

  [[providers.apis]]
  url = "https://gtfs.ovapi.nl/nl/alerts.pb"
  services = ["Alert"]
  refresh_seconds = 3600  # Fetch every hour
  frequency_minutes = 1440  # Group files in 24-hour intervals
  check_interval_seconds = 3600  # Check for new files every hour

[[providers]]
name = "york"
timezone = "Europe/London"

    # Provider-specific storage using Google Cloud Storage
    # Uncomment to use GCS for this provider only
    # [providers.storage]
    # type = "gcs"
    # [providers.storage.params]
    # bucket_name = "york-gtfs-rt-data"
    # base_path = "realtime"
    
    # Or use MinIO storage for this provider only
    # [providers.storage]
    # type = "minio"
    # [providers.storage.params]
    # endpoint = "minio.example.com:9000"
    # access_key = "your-access-key"
    # secret_key = "your-secret-key"
    # bucket_name = "york-gtfs-rt-data"
    # secure = true
    # base_path = "realtime"

    [[providers.apis]]
    url = "https://data.bus-data.dft.gov.uk/api/v1/gtfsrtdatafeed/?boundingBox=-1.1946631,53.8989899,-1.0119385,54.0195692&api_key=YOUR_API_KEY"
    services = ["VehiclePosition", "TripUpdate", "Alert"]
    refresh_seconds = 20  # Fetch every 20 seconds
    frequency_minutes = 60  # Group files in 60-minute intervals
    check_interval_seconds = 300  # Check for new files every 5 minutes 